apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-quiz-birgitte
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-quiz-birgitte
spec:
  image: "{{image}}"
  port: 8080
  liveness:
    path: /isalive
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isready
    timeout: 1
  prometheus:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  secureLogs:
    enabled: true
  kafka:
    pool: "{{ kafka_pool }}"
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
