apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-quiz-birgitte
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
    app: dp-quiz-birgitte
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /isalive
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isready
    timeout: 1
  prometheus:
    enabled: false
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 300m
      memory: 512Mi
  env:
    - name: PORT
      value: "8080"
  filesFrom:
    - secret: serviceuser-srvdp-quiz-birgitte
      mountPath: "/var/run/secrets/nais.io/service_user"
  envFrom:
    - configmap: kafka-bootstrap-servers
